### ISSUE TITLE
GUI render weird on windows

### ISSUE THREAD

**Issue by eromoe** [jiesutd/SUTDAnnotator#3]
Hi, 

I'd like to try this project, but gui is wired, looks like some resolution error:
![image](https://user-images.githubusercontent.com/3938751/27017124-af5f01a0-4f58-11e7-9ea5-8a87e52cebbe.png)

OS: win7 x64
Resolution settings:
![image](https://user-images.githubusercontent.com/3938751/27017178-17033696-4f59-11e7-9f99-5ed9e9e37d1e.png)

**Comment by jiesutd** [comment]
Hi eromoe, this is caused by some display problem of framework tkinter. There are two ways to solve it:

1. You can make the window full screen or drag the edge to enlarge the window. 
2. If the first method fails, just set the font size smaller, by modifying the 54th line of the code:
"self.textRow = 20", set the number as 18 or other smaller number. 

Please tell me if you success or fail after trying those method. 
Thank you very much.

**Comment by eromoe** [comment]
Both work, thank you!
